In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
path="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
headernames=['sepal-length','sepal-width','petal-length','petal-width','class']
dataset = pd.read_csv(path,names=headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40)


In [ ]:
#from sklearn.preprocessing import StandardScaler
#scaler=StandardScaler()
#scaler.fit(x_train)
#x_train=scaler.transform(x_train)
#x_test=scaler.transform(x_test)
#print(x_train)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
result=confusion_matrix(y_test,y_pred)
print("onfusion Matrix")
print(result)
result2=accuracy_score(y_test,y_pred)
print("accuracy",result2)

onfusion Matrix
[[19  0  0]
 [ 0 24  1]
 [ 0  0 16]]
accuracy 0.9833333333333333


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
path="/content/drive/My Drive/new dataset knn.csv"
headernames=['x1','x2','pred']
dataset = pd.read_csv(path,names=headernames)
dataset.head()

x1  x2  pred
0  x1  x2  pred
1   2   4     1
2   4   6     2
3   5   6     3
4   6   8     4

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
path="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
headernames=['sepal-length','sepal-width','petal-length','petal-width','class']
dataset = pd.read_csv(path,names=headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)
model=classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
result=confusion_matrix(y_test,y_pred)
print("confusion Matrix")
print(result)
result2=accuracy_score(y_test,y_pred)
print("accuracy",result2)

confusion Matrix
[[18  0  0]
 [ 0 25  1]
 [ 0  1 15]]
accuracy 0.9666666666666667
